<?php
/**
 * PTMD Content Workflow Service
 *
 * Creates end-to-end workflow records from topic -> case/clip asset mapping ->
 * posting queue entries, and processes due queue items for automated posting.
 */

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/social_services.php';

/**
 * Validate and normalize an upload-relative path.
 * Accepts "clips/x.mp4" or "/uploads/clips/x.mp4".
 */
function ptmd_normalize_upload_path(?string $path): string
{
    $clean = trim((string) $path);
    if ($clean === '' || str_contains($clean, "\0")) {
        return '';
    }

    $clean = str_replace('\\', '/', $clean);
    if (str_starts_with($clean, '/uploads/')) {
        $clean = substr($clean, 9);
    }
    $clean = ltrim($clean, '/');

    if ($clean === '' || str_contains($clean, '//')) {
        return '';
    }

    $segments = explode('/', $clean);
    foreach ($segments as $segment) {
        if ($segment === '' || $segment === '.' || $segment === '..') {
            return '';
        }
        if (!preg_match('/^[A-Za-z0-9_.-]+$/', $segment)) {
            return '';
        }
    }

    return implode('/', $segments);
}

function ptmd_unique_case_slug(PDO $pdo, string $title): string
{
    $base = slugify($title);
    if ($base === '') {
        $base = 'case';
    }

    $slug = $base;
    $suffix = 2;
    $checkStmt = $pdo->prepare('SELECT id FROM cases WHERE slug = :slug LIMIT 1');

    while (true) {
        $checkStmt->execute(['slug' => $slug]);
        if (!$checkStmt->fetch()) {
            return $slug;
        }
        $slug = $base . '-' . $suffix;
        $suffix++;
    }
}

function ptmd_create_case_from_topic(PDO $pdo, string $topic, ?int $createdBy = null): int
{
    $title = mb_substr(trim($topic), 0, 255);
    $slug = ptmd_unique_case_slug($pdo, $title);
    $excerpt = mb_substr('Workflow-generated draft for topic: ' . $title, 0, 500);
    $body = "Topic Brief:\n" . $topic . "\n\nGenerated by the automated content workflow for editorial review.";

    $stmt = $pdo->prepare(
        'INSERT INTO cases
         (title, slug, excerpt, body, status, created_at, updated_at)
         VALUES (:title, :slug, :excerpt, :body, "draft", NOW(), NOW())'
    );
    $stmt->execute([
        'title'   => $title,
        'slug'    => $slug,
        'excerpt' => $excerpt,
        'body'    => $body,
    ]);

    return (int) $pdo->lastInsertId();
}

/**
 * Calculate the next scheduled datetime for a platform based on active cadence rows.
 */
function ptmd_next_schedule_for_platform(PDO $pdo, string $platformDisplayName): string
{
    $stmt = $pdo->prepare(
        'SELECT day_of_week, post_time, timezone
         FROM social_post_schedules
         WHERE platform = :platform
           AND is_active = 1'
    );
    $stmt->execute(['platform' => $platformDisplayName]);
    $rows = $stmt->fetchAll();

    if (!$rows) {
        return date('Y-m-d H:i:s', strtotime('+1 hour'));
    }

    $dayToNum = [
        'Sunday' => 0, 'Monday' => 1, 'Tuesday' => 2, 'Wednesday' => 3,
        'Thursday' => 4, 'Friday' => 5, 'Saturday' => 6,
    ];

    $bestTs = null;
    foreach ($rows as $row) {
        $dayName = (string) ($row['day_of_week'] ?? '');
        if (!isset($dayToNum[$dayName])) {
            continue;
        }

        $tzName = (string) ($row['timezone'] ?? 'America/Phoenix');
        try {
            $tz = new DateTimeZone($tzName);
        } catch (Throwable $e) {
            $tz = new DateTimeZone(date_default_timezone_get());
        }

        $now = new DateTimeImmutable('now', $tz);
        $targetDow = $dayToNum[$dayName];
        $currentDow = (int) $now->format('w');
        $daysAhead = ($targetDow - $currentDow + 7) % 7;
        $datePart = $now->modify('+' . $daysAhead . ' day')->format('Y-m-d');
        $timePart = (string) ($row['post_time'] ?? '12:00:00');
        $candidate = new DateTimeImmutable($datePart . ' ' . $timePart, $tz);

        if ($candidate <= $now) {
            $candidate = $candidate->modify('+7 day');
        }

        $candidateTs = $candidate->setTimezone(new DateTimeZone(date_default_timezone_get()))->getTimestamp();
        if ($bestTs === null || $candidateTs < $bestTs) {
            $bestTs = $candidateTs;
        }
    }

    if ($bestTs === null) {
        return date('Y-m-d H:i:s', strtotime('+1 hour'));
    }

    return date('Y-m-d H:i:s', $bestTs);
}

function ptmd_workflow_caption(string $topic, array $siteOption): string
{
    $prefix = trim((string) ($siteOption['default_caption_prefix'] ?? ''));
    $hashtags = trim((string) ($siteOption['default_hashtags'] ?? ''));

    $caption = $prefix !== '' ? $prefix : 'New post from Paper Trail MD.';
    $caption = trim($caption . ' ' . $topic);
    if ($hashtags !== '') {
        $caption = trim($caption . ' ' . $hashtags);
    }

    return mb_substr($caption, 0, 2000);
}

function ptmd_sync_workflow_status(PDO $pdo, int $workflowId): void
{
    $countStmt = $pdo->prepare(
        'SELECT
            COUNT(*) AS total_count,
            SUM(CASE WHEN status = "queued" THEN 1 ELSE 0 END) AS queued_count,
            SUM(CASE WHEN status = "posted" THEN 1 ELSE 0 END) AS posted_count,
            SUM(CASE WHEN status = "failed" THEN 1 ELSE 0 END) AS failed_count
         FROM content_workflow_posts
         WHERE workflow_id = :workflow_id'
    );
    $countStmt->execute(['workflow_id' => $workflowId]);
    $counts = $countStmt->fetch() ?: [];

    $total = (int) ($counts['total_count'] ?? 0);
    $queued = (int) ($counts['queued_count'] ?? 0);
    $posted = (int) ($counts['posted_count'] ?? 0);
    $failed = (int) ($counts['failed_count'] ?? 0);

    $status = 'planned';
    if ($total > 0) {
        if ($queued > 0 && $posted === 0 && $failed === 0) {
            $status = 'queued';
        } elseif ($queued > 0) {
            $status = 'posting';
        } elseif ($failed > 0) {
            $status = 'failed';
        } else {
            $status = 'completed';
        }
    }

    $upd = $pdo->prepare(
        'UPDATE content_workflows
         SET status = :status, updated_at = NOW()
         WHERE id = :workflow_id'
    );
    $upd->execute([
        'status'      => $status,
        'workflow_id' => $workflowId,
    ]);
}

/**
 * Process due queued posts and dispatch them to platform handlers.
 */
function ptmd_process_due_social_queue(?PDO $pdo = null, int $limit = 20): array
{
    $pdo = $pdo ?: get_db();
    if (!$pdo) {
        return ['ok' => false, 'error' => 'Database unavailable'];
    }

    $limit = max(1, min(100, (int) $limit));
    $items = $pdo->query(
        'SELECT *
         FROM social_post_queue
         WHERE status IN ("queued", "scheduled")
           AND scheduled_for <= NOW()
         ORDER BY scheduled_for ASC, id ASC
         LIMIT ' . $limit
    )->fetchAll();

    $processed = 0;
    $posted = 0;
    $failed = 0;
    $queueIds = [];
    $workflowIds = [];

    foreach ($items as $item) {
        $result = dispatch_social_post($item);
        $processed++;
        $queueId = (int) $item['id'];
        $queueIds[] = $queueId;
        if (!empty($result['ok'])) {
            $posted++;
        } else {
            $failed++;
        }
    }

    if ($queueIds) {
        $postStmt = $pdo->prepare(
            'SELECT workflow_id
             FROM content_workflow_posts
             WHERE queue_id = :queue_id
             LIMIT 1'
        );
        $syncStmt = $pdo->prepare(
            'UPDATE content_workflow_posts wp
             INNER JOIN social_post_queue q ON q.id = wp.queue_id
             SET wp.status = CASE
                                WHEN q.status = "posted" THEN "posted"
                                WHEN q.status = "failed" THEN "failed"
                                WHEN q.status = "canceled" THEN "canceled"
                                ELSE "queued"
                             END,
                 wp.last_error = q.last_error,
                 wp.updated_at = NOW()
             WHERE wp.queue_id = :queue_id'
        );

        foreach ($queueIds as $queueId) {
            $syncStmt->execute(['queue_id' => $queueId]);
            $postStmt->execute(['queue_id' => $queueId]);
            $workflowId = (int) ($postStmt->fetchColumn() ?: 0);
            if ($workflowId > 0) {
                $workflowIds[$workflowId] = true;
            }
        }
    }

    foreach (array_keys($workflowIds) as $workflowId) {
        ptmd_sync_workflow_status($pdo, (int) $workflowId);
    }

    return [
        'ok'        => true,
        'processed' => $processed,
        'posted'    => $posted,
        'failed'    => $failed,
    ];
}

/**
 * Build a workflow run from a topic through queue creation.
 *
 * Input keys:
 * - topic (required)
 * - case_id (optional existing case)
 * - clip_id (optional existing clip)
 * - asset_path (optional)
 * - content_type (optional override)
 * - caption (optional override)
 * - created_by (optional admin user id)
 * - auto_dispatch (optional bool)
 */
function ptmd_run_content_workflow(array $input): array
{
    $pdo = get_db();
    if (!$pdo) {
        return ['ok' => false, 'error' => 'Database unavailable'];
    }

    $topic = trim((string) ($input['topic'] ?? ''));
    if ($topic === '') {
        return ['ok' => false, 'error' => 'Topic is required'];
    }

    $caseId = (int) ($input['case_id'] ?? 0);
    $clipId = (int) ($input['clip_id'] ?? 0);
    $createdBy = (int) ($input['created_by'] ?? 0) ?: null;
    $contentTypeOverride = trim((string) ($input['content_type'] ?? ''));
    $captionOverride = trim((string) ($input['caption'] ?? ''));
    $assetPath = ptmd_normalize_upload_path((string) ($input['asset_path'] ?? ''));
    $autoDispatch = !empty($input['auto_dispatch']);

    try {
        $pdo->beginTransaction();

        if ($caseId > 0) {
            $caseStmt = $pdo->prepare('SELECT id, video_file_path FROM cases WHERE id = :id LIMIT 1');
            $caseStmt->execute(['id' => $caseId]);
            $caseRow = $caseStmt->fetch();
            if (!$caseRow) {
                throw new RuntimeException('Selected case was not found.');
            }
        } else {
            $caseId = ptmd_create_case_from_topic($pdo, $topic, $createdBy);
            $caseRow = ['id' => $caseId, 'video_file_path' => null];
        }

        $clipRow = null;
        if ($clipId > 0) {
            $clipStmt = $pdo->prepare(
                'SELECT id, case_id, output_path, source_path
                 FROM video_clips
                 WHERE id = :id
                 LIMIT 1'
            );
            $clipStmt->execute(['id' => $clipId]);
            $clipRow = $clipStmt->fetch();
            if (!$clipRow) {
                throw new RuntimeException('Selected clip was not found.');
            }
        }

        if ($assetPath === '' && $clipRow) {
            $assetPath = ptmd_normalize_upload_path((string) ($clipRow['output_path'] ?: $clipRow['source_path']));
        }
        if ($assetPath === '' && !empty($caseRow['video_file_path'])) {
            $assetPath = ptmd_normalize_upload_path((string) $caseRow['video_file_path']);
        }

        $workflowInsert = $pdo->prepare(
            'INSERT INTO content_workflows
             (topic, case_id, source_clip_id, source_asset_path, status, created_by, created_at, updated_at)
             VALUES (:topic, :case_id, :clip_id, :asset, "planned", :created_by, NOW(), NOW())'
        );
        $workflowInsert->execute([
            'topic'      => $topic,
            'case_id'    => $caseId ?: null,
            'clip_id'    => $clipId ?: null,
            'asset'      => $assetPath !== '' ? $assetPath : null,
            'created_by' => $createdBy,
        ]);
        $workflowId = (int) $pdo->lastInsertId();

        $siteRows = $pdo->query(
            'SELECT
                ps.id AS site_id,
                ps.site_key,
                ps.display_name,
                spo.default_content_type,
                spo.default_caption_prefix,
                spo.default_hashtags
             FROM posting_sites ps
             LEFT JOIN site_posting_options spo ON spo.site_id = ps.id
             WHERE ps.is_active = 1
             ORDER BY ps.sort_order, ps.display_name'
        )->fetchAll();

        if (!$siteRows) {
            throw new RuntimeException('No active posting sites are configured.');
        }

        $queueInsert = $pdo->prepare(
            'INSERT INTO social_post_queue
             (case_id, clip_id, platform, content_type, caption, asset_path, scheduled_for, status, created_at, updated_at)
             VALUES (:case_id, :clip_id, :platform, :content_type, :caption, :asset_path, :scheduled_for, "queued", NOW(), NOW())'
        );
        $workflowPostInsert = $pdo->prepare(
            'INSERT INTO content_workflow_posts
             (workflow_id, site_id, queue_id, platform_display_name, content_type, caption, scheduled_for, status, created_at, updated_at)
             VALUES (:workflow_id, :site_id, :queue_id, :platform, :content_type, :caption, :scheduled_for, "queued", NOW(), NOW())'
        );
        $assetInsert = $pdo->prepare(
            'INSERT INTO content_workflow_assets
             (workflow_id, asset_role, asset_path, clip_id, site_id, assigned_at, created_at, updated_at)
             VALUES (:workflow_id, :asset_role, :asset_path, :clip_id, :site_id, NOW(), NOW(), NOW())'
        );

        $queueCount = 0;
        foreach ($siteRows as $site) {
            $contentType = $contentTypeOverride !== ''
                ? $contentTypeOverride
                : (trim((string) ($site['default_content_type'] ?? '')) ?: 'clip');
            $caption = $captionOverride !== ''
                ? $captionOverride
                : ptmd_workflow_caption($topic, $site);
            $scheduledFor = ptmd_next_schedule_for_platform($pdo, (string) $site['display_name']);

            $queueInsert->execute([
                'case_id'       => $caseId ?: null,
                'clip_id'       => $clipId ?: null,
                'platform'      => $site['display_name'],
                'content_type'  => $contentType,
                'caption'       => $caption,
                'asset_path'    => $assetPath !== '' ? $assetPath : null,
                'scheduled_for' => $scheduledFor,
            ]);
            $queueId = (int) $pdo->lastInsertId();

            $workflowPostInsert->execute([
                'workflow_id'   => $workflowId,
                'site_id'       => (int) $site['site_id'],
                'queue_id'      => $queueId,
                'platform'      => $site['display_name'],
                'content_type'  => $contentType,
                'caption'       => $caption,
                'scheduled_for' => $scheduledFor,
            ]);

            if ($assetPath !== '') {
                $assetInsert->execute([
                    'workflow_id' => $workflowId,
                    'asset_role'  => $clipId > 0 ? 'clip_video' : 'primary_video',
                    'asset_path'  => $assetPath,
                    'clip_id'     => $clipId ?: null,
                    'site_id'     => (int) $site['site_id'],
                ]);
            }

            $queueCount++;
        }

        $pdo->prepare(
            'UPDATE content_workflows
             SET status = "queued",
                 notes = :notes,
                 updated_at = NOW()
             WHERE id = :id'
        )->execute([
            'notes' => 'Generated queue items: ' . $queueCount,
            'id'    => $workflowId,
        ]);

        $pdo->commit();

        $dispatchSummary = null;
        if ($autoDispatch) {
            $dispatchSummary = ptmd_process_due_social_queue($pdo, 25);
        }
        ptmd_sync_workflow_status($pdo, $workflowId);

        return [
            'ok' => true,
            'workflow_id' => $workflowId,
            'case_id' => $caseId,
            'clip_id' => $clipId ?: null,
            'queue_count' => $queueCount,
            'dispatch' => $dispatchSummary,
        ];
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        return ['ok' => false, 'error' => $e->getMessage()];
    }
}
